// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7egy1aTcrgeahu3HMi_QmmkhkM6cedoI',
    appId: '1:946716758365:web:a8feb5e54e495f3ef898b4',
    messagingSenderId: '946716758365',
    projectId: 'belka-app-6fb58',
    authDomain: 'belka-app-6fb58.firebaseapp.com',
    storageBucket: 'belka-app-6fb58.firebasestorage.app',
    measurementId: 'G-YRQEFWZLVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwQjlH2TaneAJDVWkBtUpUF8vWnpmmxQ',
    appId: '1:946716758365:android:daf80f4c64f80939f898b4',
    messagingSenderId: '946716758365',
    projectId: 'belka-app-6fb58',
    storageBucket: 'belka-app-6fb58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYHSfncDMRaN2FNMz0FyoB0oOqShBK1Q',
    appId: '1:946716758365:ios:f71a3c1cb016e319f898b4',
    messagingSenderId: '946716758365',
    projectId: 'belka-app-6fb58',
    storageBucket: 'belka-app-6fb58.firebasestorage.app',
    iosBundleId: 'com.example.belkaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYHSfncDMRaN2FNMz0FyoB0oOqShBK1Q',
    appId: '1:946716758365:ios:f71a3c1cb016e319f898b4',
    messagingSenderId: '946716758365',
    projectId: 'belka-app-6fb58',
    storageBucket: 'belka-app-6fb58.firebasestorage.app',
    iosBundleId: 'com.example.belkaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7egy1aTcrgeahu3HMi_QmmkhkM6cedoI',
    appId: '1:946716758365:web:f5b5702dd8df9f50f898b4',
    messagingSenderId: '946716758365',
    projectId: 'belka-app-6fb58',
    authDomain: 'belka-app-6fb58.firebaseapp.com',
    storageBucket: 'belka-app-6fb58.firebasestorage.app',
    measurementId: 'G-WCD1PYWZW1',
  );
}
